# Generated by Django 6.0 on 2026-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('RH', 'Ressources Humaines'), ('MANAGER', 'Manager'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=20),
        ),
    ]
