# Generated by Django 6.0 on 2026-01-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprh', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='needs_renewal',
            field=models.BooleanField(default=False, verbose_name='À renouveler'),
        ),
    ]
