# Generated by Django 6.0 on 2026-01-09 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprh', '0006_evaluation_presencetracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(verbose_name='Exigences')),
                ('position', models.CharField(max_length=100, verbose_name='Poste')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('FREELANCE', 'Freelance')], max_length=20, verbose_name='Type de contrat')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publiée'), ('CLOSED', 'Fermée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('max_applications', models.IntegerField(blank=True, null=True, verbose_name='Nombre maximum de candidatures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historiques de paiement',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayslipBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('PERFORMANCE', 'Prime de performance'), ('PROJECT', 'Prime de projet'), ('OVERTIME', 'Heures supplémentaires'), ('BONUS', 'Bonus'), ('COMMISSION', 'Commission'), ('ALLOWANCE', 'Indemnité'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de prime')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prime',
                'verbose_name_plural': 'Primes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayslipDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('TAX', 'Impôt'), ('SOCIAL_SECURITY', 'Sécurité sociale'), ('INSURANCE', 'Assurance'), ('RETIREMENT', 'Retraite'), ('LOAN', 'Prêt'), ('ADVANCE', 'Avance'), ('ABSENCE', 'Absence'), ('LATE', 'Retard'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de déduction')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Déduction',
                'verbose_name_plural': 'Déductions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('training_type', models.CharField(choices=[('INTERNAL', 'Interne'), ('EXTERNAL', 'Externe'), ('ONLINE', 'En ligne'), ('WORKSHOP', 'Atelier'), ('CONFERENCE', 'Conférence'), ('CERTIFICATION', 'Certification')], default='INTERNAL', max_length=20, verbose_name='Type')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Organisme de formation')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('duration_hours', models.IntegerField(blank=True, null=True, verbose_name='Durée (heures)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20, verbose_name='Statut')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training/certificates/', verbose_name='Certificat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du plan')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('objectives', models.TextField(verbose_name='Objectifs')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de formation',
                'verbose_name_plural': 'Plans de formation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Date de la session')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('instructor', models.CharField(blank=True, max_length=200, verbose_name='Formateur')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('attendance', models.BooleanField(default=False, verbose_name='Présence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session de formation',
                'verbose_name_plural': 'Sessions de formation',
                'ordering': ['session_date', 'start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='employeehistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Historique des changements', 'verbose_name_plural': 'Historiques des changements'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Entretien', 'verbose_name_plural': 'Entretiens'},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'verbose_name': 'Solde de congés', 'verbose_name_plural': 'Soldes de congés'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de congé', 'verbose_name_plural': 'Demandes de congé'},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Fiche de paie', 'verbose_name_plural': 'Fiches de paie'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de candidature'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='availability_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de disponibilité'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='candidates/cover_letters/', verbose_name='Lettre de motivation'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire attendu'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.IntegerField(default=0, help_text='Note globale sur 10', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Source (LinkedIn, site web, etc.)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='auto_renewal',
            field=models.BooleanField(default=False, verbose_name='Renouvellement automatique'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='apprh.contract', verbose_name="Contrat d'origine"),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_notice_days',
            field=models.IntegerField(default=30, help_text='Nombre de jours avant expiration pour alerter'),
        ),
        migrations.AddField(
            model_name='employee',
            name='badge_id',
            field=models.CharField(blank=True, help_text='ID du badge pour pointage automatique', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='change_type',
            field=models.CharField(choices=[('POSITION', 'Changement de poste'), ('SALARY', 'Changement de salaire'), ('SERVICE', 'Changement de service'), ('CONTRACT', 'Changement de contrat'), ('STATUS', 'Changement de statut'), ('INFO', "Modification d'information"), ('OTHER', 'Autre')], default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du changement'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='areas_for_improvement',
            field=models.TextField(blank=True, verbose_name="Axes d'amélioration"),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='communication_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Communication'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='goals',
            field=models.TextField(blank=True, verbose_name='Objectifs pour la prochaine période'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='initiative_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Initiative'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='manager_feedback',
            field=models.TextField(blank=True, verbose_name='Feedback du manager'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='manager_recommendations',
            field=models.TextField(blank=True, verbose_name='Recommandations du manager'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='productivity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Productivité'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='quality_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Qualité du travail'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('APPROVED', 'Approuvée')], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='strengths',
            field=models.TextField(blank=True, verbose_name='Points forts'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='teamwork_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name="Travail d'équipe"),
        ),
        migrations.AddField(
            model_name='interview',
            name='actual_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date réelle'),
        ),
        migrations.AddField(
            model_name='interview',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, verbose_name='Lien de réunion (vidéo)'),
        ),
        migrations.AddField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('STRONG_YES', 'Fortement recommandé'), ('YES', 'Recommandé'), ('MAYBE', 'Peut-être'), ('NO', 'Non recommandé')], max_length=20, verbose_name='Recommandation'),
        ),
        migrations.AddField(
            model_name='interview',
            name='strengths',
            field=models.TextField(blank=True, verbose_name='Points forts'),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='weaknesses',
            field=models.TextField(blank=True, verbose_name='Points à améliorer'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Raison du rejet (Manager)'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rh_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rh_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Raison du rejet (RH)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salaire brut'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Heures supplémentaires'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='presencetracking',
            name='badge_id',
            field=models.CharField(blank=True, help_text='ID du badge pour pointage automatique', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='presencetracking',
            name='check_in_method',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('BADGE', 'Badge'), ('MOBILE', 'Application mobile'), ('WEB', 'Interface web')], default='MANUAL', max_length=20, verbose_name='Méthode de pointage'),
        ),
        migrations.AddField(
            model_name='presencetracking',
            name='expected_check_in',
            field=models.TimeField(blank=True, default='09:00', help_text="Heure d'arrivée attendue", null=True),
        ),
        migrations.AddField(
            model_name='presencetracking',
            name='expected_check_out',
            field=models.TimeField(blank=True, default='18:00', help_text='Heure de départ attendue', null=True),
        ),
        migrations.AddField(
            model_name='presencetracking',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures supplémentaires', max_digits=5),
        ),
        migrations.AddField(
            model_name='presencetracking',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures travaillées', max_digits=5),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='candidates/cv/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Poste recherché'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('SCREENING', 'Présélection'), ('INTERVIEW', 'Entretien'), ('SECOND_INTERVIEW', 'Second entretien'), ('FINAL_REVIEW', 'Évaluation finale'), ('OFFER_SENT', 'Offre envoyée'), ('OFFER_ACCEPTED', 'Offre acceptée'), ('OFFER_REJECTED', 'Offre refusée'), ('HIRED', 'Embauché'), ('REJECTED', 'Rejeté'), ('WITHDRAWN', 'Retiré')], default='NEW', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Commentaires généraux'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Évalué par'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.CharField(choices=[('ANNUAL', 'Annuelle'), ('SEMESTRIAL', 'Semestrielle'), ('QUARTERLY', 'Trimestrielle'), ('MONTHLY', 'Mensuelle'), ('PROJECT', 'Projet'), ('PROMOTION', 'Promotion')], default='ANNUAL', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, help_text='Note globale sur 5', max_digits=3, verbose_name='Note globale'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('PHONE', 'Téléphonique'), ('VIDEO', 'Vidéoconférence'), ('ONSITE', 'Sur site'), ('TECHNICAL', 'Technique'), ('HR', 'RH'), ('MANAGER', 'Manager'), ('FINAL', 'Final')], default='ONSITE', max_length=20, verbose_name="Type d'entretien"),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Intervieweur'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='rating',
            field=models.IntegerField(default=0, help_text='Note sur 10', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='Date prévue'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('RESCHEDULED', 'Reprogrammé')], default='SCHEDULED', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='annual_leave',
            field=models.IntegerField(default=25, verbose_name='Congés annuels alloués'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.IntegerField(default=10, verbose_name='Congés maladie alloués'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_annual',
            field=models.IntegerField(default=0, verbose_name='Congés annuels utilisés'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_sick',
            field=models.IntegerField(default=0, verbose_name='Congés maladie utilisés'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='days',
            field=models.IntegerField(help_text='Nombre de jours de congé'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Congé annuel'), ('SICK', 'Congé maladie'), ('PERSONAL', 'Congé personnel'), ('MATERNITY', 'Congé maternité'), ('PATERNITY', 'Congé paternité'), ('UNPAID', 'Congé sans solde')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='manager_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par (Manager)'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(verbose_name='Raison du congé'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rh_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par (RH)'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('MANAGER_APPROVED', 'Approuvé par le manager'), ('RH_APPROVED', 'Approuvé par RH'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total primes'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total déductions'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('GENERATED', 'Généré'), ('SENT', 'Envoyé'), ('PAID', 'Payé')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='presencetracking',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'En retard'), ('EARLY_LEAVE', 'Départ anticipé'), ('ON_LEAVE', 'En congé')], default='PRESENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='presencetracking',
            index=models.Index(fields=['date', 'employee'], name='apprh_prese_date_68f27f_idx'),
        ),
        migrations.AddIndex(
            model_name='presencetracking',
            index=models.Index(fields=['badge_id'], name='apprh_prese_badge_i_34c563_idx'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offers', to='apprh.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='apprh.joboffer', verbose_name="Offre d'emploi"),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='apprh.payslip'),
        ),
        migrations.AddField(
            model_name='payslipbonus',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to='apprh.payslip'),
        ),
        migrations.AddField(
            model_name='payslipdeduction',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_items', to='apprh.payslip'),
        ),
        migrations.AddField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='apprh.employee'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='apprh.employee'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='apprh.trainingplan'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='apprh.training'),
        ),
    ]
