# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprh', '0007_joboffer_paymenthistory_payslipbonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cnps_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNPS'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('', 'Non renseigné')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', 'Non renseigné'), ('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf(ve)'), ('PACS', 'PACS')], max_length=20, verbose_name='Situation familiale'),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('', 'Non renseigné'), ('CNI', "Carte nationale d'identité"), ('PASSPORT', 'Passeport'), ('OTHER', 'Autre')], max_length=20, verbose_name="Type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de pièce d\'identité'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de délivrance de la pièce'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_exit',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qualification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (travailleurs étrangers)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name="N° d'ordre (titre)"),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_apprentice',
            field=models.BooleanField(default=False, verbose_name='Apprentissage'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_professionalization_contract',
            field=models.BooleanField(default=False, verbose_name='Professionnalisation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_cdd',
            field=models.BooleanField(default=False, verbose_name='CDD'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_part_time',
            field=models.BooleanField(default=False, verbose_name='Temps partiel'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_specific_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Autre (contrat spécifique)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Emploi'),
        ),
    ]
