# Generated by Django 6.0.1 on 2026-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprh', '0008_employee_registre_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_hire',
            field=models.DateField(verbose_name="Date d'entrée"),
        ),
    ]
