# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprh', '0009_alter_employee_date_of_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de sécurité sociale'),
        ),
    ]
